services:
  hhvm:
    container_name: theodore-static-type-assertion-code-generator-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /mnt/project
    ports:
      - 48558:10641
