name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    # Run every day at 6:14PM
    - cron: '14 18 * * *'
jobs:
  build:
    name: HHVM ${{matrix.hhvm}} - ${{matrix.os}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        hhvm:
          # Instead of testing in 4.73, we test in hhvm 4.74
          # This version fixed a bug where hh_client wouldn't understand shape keys with quotes
          # The tests do pass on hhvm 4.73 with version_compare.
          # The hhvm/actions/hack-lint-test action runs hh_client before hacktest.
          # For this reason, we can not test on 4.73.
          # If you find a bug on 4.73 which is not found by the test suite, open an issue on github.
          - '4.74'
          - latest
          - nightly
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create branch for version alias
        run: git checkout -b CI_current_pull_request
      - uses: hhvm/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}